name: Node CI

# 指定触发action的事件
on:
  push:
    # 指定触发指定事件的分支 仅master触发
    branches:
      - main
  pull_request:   # 待测试
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ strategy.matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ strategy.matrix.node-version }}
    - name: 执行npm install
      run: |
        npm install
      env:
        CI: true
    - name: 执行npm run build
      run: |
        npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist